import DashboardLayout from '@/DashboardLayout';
import { Container, Toolbar } from '@mui/material';
import { DataGrid } from '@mui/x-data-grid';
import Title from './../../../../components/Title/Title';
import Head from 'next/head';

const columns = [
  { field: 'id', headerName: 'ID', width: 70 },
  { field: 'firstName', headerName: 'First name', width: 130 },
  { field: 'lastName', headerName: 'Last name', width: 130 },
  {
    field: 'age',
    headerName: 'Age',
    type: 'number',
    width: 90,
  },
  {
    field: 'fullName',
    headerName: 'Full name',
    description: 'This column has a value getter and is not sortable.',
    sortable: false,
    width: 160,
    valueGetter: (params) =>
      `${params.row.firstName || ''} ${params.row.lastName || ''}`,
  },
];

const rows = [
  { id: 1, lastName: 'Snow', firstName: 'Jon', age: 35 }
];

export default function TeacherRequest() {
  return (
    <DashboardLayout>
                    <Head>
    <title>EduPulse || Teacher Request</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <Toolbar />
    <Title title={'Teacher Request'} />
    <Container maxWidth='xl' align='center' style={{ marginTop:'2rem' }}>
      <DataGrid
        rows={rows}
        columns={columns}
        initialState={{
          pagination: {
            paginationModel: { page: 0, pageSize: 5 },
          },
        }}
        pageSizeOptions={[5, 10]}
        checkboxSelection
      />
    </Container>
    </DashboardLayout>
  );
}