import DashboardLayout from '@/DashboardLayout';
import { Container, Toolbar, Button, Avatar } from '@mui/material';
import { DataGrid } from '@mui/x-data-grid';
import Title from './../../../../components/Title/Title';
import Head from 'next/head';
import { useContext } from 'react';
import { AuthContext } from '@/Provider/AuthProvider';
import Image from 'next/image';



export default function TeacherRequest() {

    const { user } = useContext(AuthContext);

    const columns = [
      { field: 'id', headerName: 'ID', width: 70 },
      {
        field: 'image',
        headerName: 'Image',
        width: 60,
        renderCell: (params) => (
<div style={{ width: 60, height: 60, borderRadius: '50%', overflow: 'hidden' }}>
        <Image
          src={params.row.image || ''}
          alt={`Image for ${params.row.fullName}`}
          layout="fill"
          objectFit="cover"
        />
      </div>
        ),
      },
      { field: 'fullName', headerName: 'Name', width: 130 },
      { field: 'experience', headerName: 'Experience', width: 130 },
      { field: 'title', headerName: 'Title', width: 130 },
      { field: 'category', headerName: 'Category', width: 130 },
      { field: 'status', headerName: 'Status', width: 130 },
      {
        field: 'actions',
        headerName: 'Actions',
        width: 180,
        renderCell: (params) => (
          <div style={{ display: 'flex', gap: '4px' }}>
            <Button variant="contained" color="primary" size="small" onClick={() => handleApprove(params.row.id)}>
              Approve
            </Button>
            <Button variant="contained" color="secondary" size="small" onClick={() => handleReject(params.row.id)}>
              Reject
            </Button>
          </div>
        ),
      },
    ];
  console.log(user?.photoURL)
    const rows = [
      {
        id: 1,
        lastName: 'Snow',
        firstName: 'Jon',
        age: 35,
        image: (
          <Avatar alt="Remy Sharp" src={user?.photoURL} sx={{ width: 60, height: 60 }} />
        ),
        experience: '5 years',
        title: 'Math Teacher',
        category: 'Mathematics',
        status: 'Pending',
      },
    ];
  
    const handleApprove = (id) => {
      console.log(`Teacher with ID ${id} approved`);
    };
  
    const handleReject = (id) => {
      console.log(`Teacher with ID ${id} rejected`);
    };
  
  return (
    <DashboardLayout>
      <Head>
        <title>EduPulse || Teacher Request</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />
      <Title title={'Teacher Request'} />
      <Container maxWidth="lg" align="center" style={{ marginTop: '2rem' }}>
      <DataGrid
  rows={rows}
  columns={columns}
  initialState={{
    pagination: {
      paginationModel: { page: 0, pageSize: 5 },
    },
  }}
  pageSizeOptions={[5, 10]}
/>
      </Container>
    </DashboardLayout>
  );
}
