import DashboardLayout from "@/DashboardLayout";
import { Avatar, Button, Container, Toolbar, Typography } from "@mui/material";
import { DataGrid, GridColDef, GridRenderCellParams } from "@mui/x-data-grid";
import Head from "next/head";
import { useQuery } from "@tanstack/react-query";
import useAxiosSecure from "@/hooks/useAxiosSecure";
import loading from "../../../../assets/Loading/loading.json";
import Swal from "sweetalert2";
import useCurrentUser from "@/hooks/useCurrentUser";
import dynamic from "next/dynamic";
import GroupsRoundedIcon from "@mui/icons-material/GroupsRounded";
import {
  AdminPageHeader,
  AdminTableCard,
  RoleBadge,
  adminDataGridSx,
  adminPageSx,
  approveButtonSx,
} from "@/components/DashboardCompo/adminPanelStyles";

const Lottie = dynamic(() => import("lottie-react"), { ssr: false });

type UserRow = {
  _id: string;
  image?: string;
  name?: string;
  fullName?: string;
  email: string;
  role: string;
};

const Users = () => {
  const axiosSecure = useAxiosSecure();
  const { currentUser } = useCurrentUser();
  const {
    data: allUsers = [],
    refetch,
    isLoading,
  } = useQuery<UserRow[]>({
    queryKey: ["users"],
    queryFn: async () => {
      const res = await axiosSecure.get("/user");
      return res.data;
    },
  });

  if (isLoading) {
    return (
      <Container
        sx={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Lottie animationData={loading} />
      </Container>
    );
  }

  const handleMakeAdmin = async (id: string) => {
    const result = await Swal.fire({
      title: "Are you sure?",
      text: "Do you want to give the admin role to this user?",
      icon: "warning",
      showCancelButton: true,
      confirmButtonText: "Make Admin",
      cancelButtonText: "Cancel",
    });

    if (result.isConfirmed) {
      const res = await axiosSecure.patch<{ modifiedCount?: number }>(
        `/user/admin/${id}`
      );

      if (res.data.modifiedCount && res.data.modifiedCount > 0) {
        refetch();
        await Swal.fire({
          title: "User got the admin role!",
          icon: "success",
          confirmButtonText: "OK",
        });
      } else {
        await Swal.fire({
          title: "User role is not changed",
          icon: "info",
          confirmButtonText: "OK",
        });
      }
    }
  };

  const columns: GridColDef<UserRow>[] = [
    {
      field: "image",
      headerName: "Image",
      width: 92,
      renderCell: (params: GridRenderCellParams<UserRow>) => (
        <Avatar
          src={params.row.image}
          alt={`Image for ${params.row.fullName ?? params.row.name ?? "user"}`}
          sx={{
            width: 48,
            height: 48,
            border: "3px solid #fff",
            boxShadow: "0 8px 18px rgba(16, 24, 40, 0.12)",
          }}
        >
          {(params.row.fullName ?? params.row.name ?? "U").charAt(0)}
        </Avatar>
      ),
    },
    {
      field: "name",
      headerName: "Name",
      minWidth: 180,
      flex: 0.8,
      renderCell: (params: GridRenderCellParams<UserRow>) => (
        <Typography sx={{ color: "#101828", fontWeight: 800 }}>
          {params.row.name ?? params.row.fullName}
        </Typography>
      ),
    },
    {
      field: "email",
      headerName: "Email",
      minWidth: 240,
      flex: 1,
      renderCell: (params: GridRenderCellParams<UserRow>) => (
        <Typography noWrap sx={{ color: "#475467", fontWeight: 700 }}>
          {params.row.email}
        </Typography>
      ),
    },
    {
      field: "role",
      headerName: "Role",
      minWidth: 140,
      renderCell: (params: GridRenderCellParams<UserRow>) => (
        <RoleBadge role={params.row.role} />
      ),
    },
    {
      field: "actions",
      headerName: "Actions",
      minWidth: 180,
      renderCell: (params: GridRenderCellParams<UserRow>) => (
        <Button
          variant="contained"
          disabled={params.row.role === "admin"}
          size="small"
          sx={approveButtonSx}
          onClick={
            params.row.role === "admin"
              ? undefined
              : () => handleMakeAdmin(params.row._id)
          }
        >
          Make Admin
        </Button>
      ),
    },
  ];

  if (currentUser) {
    return (
      <DashboardLayout>
        <Head>
          <title>All Users || EduPulse </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Toolbar />
        <Container maxWidth={false} disableGutters sx={adminPageSx}>
          <AdminPageHeader
            eyebrow="User management"
            title="All Our Users"
            subtitle="Manage account roles with clearer identity, email, and role presentation."
            icon={<GroupsRoundedIcon />}
          />
          <AdminTableCard
            title="User directory"
            subtitle="The existing make-admin action remains available for eligible users."
            minWidth={860}
          >
            <DataGrid
              rows={allUsers}
              columns={columns}
              getRowId={(row) => row._id}
              initialState={{
                pagination: {
                  paginationModel: { page: 0, pageSize: 5 },
                },
              }}
              pageSizeOptions={[5, 10]}
              rowHeight={76}
              columnHeaderHeight={58}
              autoHeight
              sx={adminDataGridSx}
            />
          </AdminTableCard>
        </Container>
      </DashboardLayout>
    );
  }

  return null;
};

export default Users;
