import DashboardLayout from "@/DashboardLayout";
import { Container, Toolbar, Button } from "@mui/material";
import { DataGrid, GridColDef, GridRenderCellParams } from "@mui/x-data-grid";
import Title from "../../../../components/Title/Title";
import Head from "next/head";
import { useQuery } from "@tanstack/react-query";
import useAxiosSecure from "@/hooks/useAxiosSecure";
import Image from "next/image";
import loading from "../../../../assets/Loading/loading.json";
import Swal from "sweetalert2";
import useCurrentUser from "@/hooks/useCurrentUser";
import dynamic from "next/dynamic";

const Lottie = dynamic(() => import("lottie-react"), { ssr: false });

type UserRow = {
  _id: string;
  image?: string;
  name?: string;
  fullName?: string;
  email: string;
  role: string;
};

const Users = () => {
  const axiosSecure = useAxiosSecure();
  const { currentUser } = useCurrentUser();
  const {
    data: allUsers = [],
    refetch,
    isLoading,
  } = useQuery<UserRow[]>({
    queryKey: ["users"],
    queryFn: async () => {
      const res = await axiosSecure.get("/user");
      return res.data;
    },
  });

  if (isLoading) {
    return (
      <Container
        sx={{
          height: "100vh",
          display: "flex",
          justifyContent: "center",
          alignItems: "center",
        }}
      >
        <Lottie animationData={loading} />
      </Container>
    );
  }

  const handleMakeAdmin = async (id: string) => {
    const result = await Swal.fire({
      title: "Are you sure?",
      text: "Do you want to give the admin role to this user?",
      icon: "warning",
      showCancelButton: true,
      confirmButtonText: "Make Admin",
      cancelButtonText: "Cancel",
    });

    if (result.isConfirmed) {
      const res = await axiosSecure.patch<{ modifiedCount?: number }>(
        `/user/admin/${id}`
      );

      if (res.data.modifiedCount && res.data.modifiedCount > 0) {
        refetch();
        await Swal.fire({
          title: "User got the admin role!",
          icon: "success",
          confirmButtonText: "OK",
        });
      } else {
        await Swal.fire({
          title: "User role is not changed",
          icon: "info",
          confirmButtonText: "OK",
        });
      }
    }
  };

  const columns: GridColDef<UserRow>[] = [
    {
      field: "image",
      headerName: "Image",
      width: 60,
      renderCell: (params: GridRenderCellParams<UserRow>) =>
        params.row.image ? (
          <Image
            src={params.row.image}
            width={96}
            height={96}
            alt={`Image for ${params.row.fullName ?? params.row.name ?? "user"}`}
            style={{
              width: "100%",
              height: "auto",
              objectFit: "cover",
              borderRadius: "70%",
            }}
          />
        ) : null,
    },
    { field: "name", headerName: "Name", width: 150 },
    { field: "email", headerName: "Email", width: 180 },
    { field: "role", headerName: "Role", width: 130 },
    {
      field: "actions",
      headerName: "Actions",
      width: 180,
      renderCell: (params: GridRenderCellParams<UserRow>) => (
        <div style={{ display: "flex", gap: "4px" }}>
          {params.row.role === "admin" ? (
            <Button variant="contained" disabled color="primary" size="small">
              Make Admin
            </Button>
          ) : (
            <Button
              variant="contained"
              color="primary"
              size="small"
              onClick={() => handleMakeAdmin(params.row._id)}
            >
              Make Admin
            </Button>
          )}
        </div>
      ),
    },
  ];

  if (currentUser) {
    return (
      <DashboardLayout>
        <Head>
          <title>All Users || EduPulse </title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Toolbar />
        <Title title={"All Our Users"} />
        <Container
          maxWidth="md"
          sx={{
            display: "flex",
            justifyContent: "center",
            alignItems: "center",
            mt: "1rem",
          }}
        >
          <DataGrid
            rows={allUsers}
            columns={columns}
            getRowId={(row) => row._id}
            initialState={{
              pagination: {
                paginationModel: { page: 0, pageSize: 5 },
              },
            }}
            pageSizeOptions={[5, 10]}
            style={{ width: "fit-content" }}
          />
        </Container>
      </DashboardLayout>
    );
  }

  return null;
};

export default Users;
