import Head from "next/head";
import { Toolbar } from "@mui/material";
import Banner from './../components/HomePage/Banner';
import Trusted from "@/components/HomePage/Trusted";
import PopularCourses from "@/components/HomePage/PopularCourses";
import FeedBack from "@/components/HomePage/FeedBack";
import TotalUserSection from "@/components/HomePage/TotalUserSection";
import WhyChooseUs from "@/components/HomePage/WhyChooseUs/WhyChooseUs";
import Faq from './../components/HomePage/Faq';
import Teacher from './../components/HomePage/Teacher';

export default function Home() {
  return (
    <>
      <Head>
        <title>Course || Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />
      <Banner />
      <div style={{ marginTop: "4rem", marginBottom: "4rem" }}>
        <Trusted />
      </div>{" "}
      <PopularCourses />
      <FeedBack />
      <TotalUserSection />
      <WhyChooseUs />
      <Teacher />
      <Faq />
    </>
  );
}