import Head from "next/head";
import { Toolbar } from "@mui/material";
import Banner from "./HomePage/Banner";
import Trusted from "./HomePage/Trusted";
import PopularCourses from "./HomePage/PopularCourses";
import FeedBack from "./HomePage/FeedBack";
import TotalUserSection from './HomePage/TotalUserSection';
import WhyChooseUs from "./HomePage/WhyChooseUs/WhyChooseUs";
import Faq from './HomePage/Faq';

export default function Home() {
  return (
    <>
      <Head>
        <title>Course || Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />
      <Banner />
      <div style={{ marginTop: "4rem", marginBottom: "4rem" }}>
        <Trusted />
      </div>{" "}
      <PopularCourses />
      <FeedBack />
      <TotalUserSection />
      <WhyChooseUs />
      <Faq />
    </>
  );
}