import Head from 'next/head';
import { Toolbar } from '@mui/material';
import Banner from './HomePage/Banner';
import Trusted from './HomePage/Trusted';


export default function Home() {
  return (
    <>
      <Head>
        <title>Course || Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />

      <Banner />
      <Trusted />
    </>
  );
}
