import DashboardLayout from '@/DashboardLayout'
import userCurrentUser from '@/hooks/userCurrentUser'
import { Toolbar } from '@mui/material'
import Head from 'next/head'
import React from 'react'

export default function Profile() {
const {currentUser, refetch } = userCurrentUser()
console.log(currentUser)

  return (
    <DashboardLayout>
        <Head>
    <title>Profile || EduPulse </title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
      <Toolbar />
     Profile
    </DashboardLayout>
  )
}
