import DashboardLayout from '@/DashboardLayout'
import useCurrentUser from '@/hooks/useCurrentUser'
import { Container, Toolbar } from '@mui/material'
import Lottie from 'lottie-react'
import Head from 'next/head'
import loading from '../../../assets/Loading/loading.json'

const Profile = () => {
const {currentUser, refetch, isLoading } = useCurrentUser()

console.log(currentUser)


if (isLoading) {
  return (
    <Container
      sx={{
        height: "100vh",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Lottie animationData={loading} />
    </Container>
  );
}

if(currentUser?.length === 0){
  refetch()
}

  return (
    <DashboardLayout>
        <Head>
    <title>Profile || EduPulse </title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
      <Toolbar />
     Profile
    </DashboardLayout>
  )
}

export default Profile