import DashboardLayout from '@/DashboardLayout';
import { Container, Toolbar, Button, Avatar } from '@mui/material';
import { DataGrid } from '@mui/x-data-grid';
import Title from './../../../../components/Title/Title';
import Head from 'next/head';
import Image from 'next/image';

export default function index() {




const handleApprove = id => {
console.log('approve')
}
const handleReject = id => {
console.log('Reject')
}



  const columns = [
    { field: 'id', headerName: 'ID', width: 80 },
    {
      field: 'image',
      headerName: 'Image',
      width: 60,
      renderCell: (params) => (
<div style={{ width: 60, height: 60, borderRadius: '50%', overflow: 'hidden' }}>
        <Image
          src={params.row.image || ''}
          alt={`Image for ${params.row.fullName}`}
          layout="fill"
          objectFit="cover"
        />
      </div>
      ),
    },
    { field: 'title', headerName: 'Title', width: 150 },
    { field: 'email', headerName: 'Email', width: 180 },
    { field: 'description', headerName: 'Description', width: 130 },
    { field: 'status', headerName: 'Status', width: 130 },
    {
      field: 'actions',
      headerName: 'Actions',
      width: 180,
      renderCell: (params) => (
        <div style={{ display: 'flex', gap: '4px' }}>
          <Button variant="contained" color="primary" size="small" onClick={() => handleApprove(params.row.id)}>
            Approve
          </Button>
          <Button variant="contained" color="error" size="small" onClick={() => handleReject(params.row.id)}>
            Reject
          </Button>
        </div>
      ),
    },
  ];
  const rows = [
    {
      id: 1,
      title:'rafi',
      email: 'rafimd2222@gmail.com' ,
      image: (
        <Avatar alt="Remy Sharp" src={''} sx={{ width: 60, height: 60 }} />
      ),
      role:'student',
      actions: 'actions',
      status:'pending'
    },
  ];


  return (
    <DashboardLayout>
                            <Head>
    <title>EduPulse || All Classes</title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
      <Toolbar />
   <Title title={'All Classes'} />
   <Container maxWidth='lg' sx={{display:'flex', justifyContent:'center', alignItems:'center', mt:'1rem'}}>
<DataGrid  
      rows={rows}
      columns={columns}
      initialState={{
        pagination: {
          paginationModel: { page: 0, pageSize: 5 },
        },
      }}
      pageSizeOptions={[5, 10]}
      style={{ width: 'fit-content'}}
    />
</Container>
    </DashboardLayout>
  )
}
