import DashboardLayout from "@/DashboardLayout"
import { Toolbar } from '@mui/material';
import Head from "next/head";
import Title from './../../../../components/Title/Title';
import { Margin } from "@mui/icons-material";

const EnrollClass = () => {
  return (
    <DashboardLayout>
        <Head>
    <title>Enrolled Classes || EduPulse </title>
    <meta name="description" content="Generated by create next app" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
      <Toolbar />
      <Title title={'My Enrolled'} titleColor={' Class'}/>


      <div style={{margin:'6rem'}}>
        This page is under construction
      </div>
    </DashboardLayout>
  )
}

export default EnrollClass
